name = "luxury-international"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "luxury-international-db"
database_id = "29520352-16e5-44d4-b4cd-3ee0027187a6"